apps/doadores/urls.py
from django.urls import path
from . import views

app_name = 'doadores'

urlpatterns = [
    path('', views.list_doadores, name='list_doadores'),
    path('adicionar/', views.add_doador, name='add_doador'),
    path('editar/<int:id_doador>/', views.edit_doador, name='edit_doador'),
    path('excluir/<int:id_doador>/', views.delete_doador, name='delete_doador'),
]

projetoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('accounts.urls', namespace='accounts')),
    path('adocoes/', include('adocoes.urls', namespace='adocoes')),
    path('atendimentos/', include('atendimentos.urls', namespace='atendimentos')),
    path('animais/', include('animais.urls', namespace='animais')),
    path('adotantes/', include('adotantes.urls', namespace='adotantes')),
    path('doadores/', include('doadores.urls', namespace='doadores')),
    path('ongs/', include('ongs.urls', namespace='ongs')),
    path('veterinarios/', include('veterinarios.urls', namespace='veterinarios')),
    path('', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/doadores/models.py
from django.db import models

# Create your models here.

class Doador(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    name = models.CharField('Nome', max_length=50)
    cpf = models.CharField('Cpf', max_length=11)
    address = models.CharField('Endereco', max_length=50)
    phone = models.CharField('Telefone', max_length=11)
    
    class Meta:
        verbose_name = 'Doador'
        verbose_name_plural = 'Doadores'
        ordering =['id']

    def __str__(self):
        return self.name

apps/doadores/forms.py
from django import forms
from .models import Doador

class DoadorForm(forms.ModelForm):

    class Meta:
        model = Doador
        exclude = ('created_on' , 'updated_on',)

apps/doadores/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from .forms import DoadorForm
from .models import Doador
from django.contrib.auth.decorators import login_required
# Create your views here.

def add_doador(request):
    template_name = 'doadores/add_doador.html'
    context = {}
    if request.method == 'POST':
        form = DoadorForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('animais:add_animal')
    form = DoadorForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_doadores(request):
    template_name = 'doadores/list_doadores.html'
    doadores = Doador.objects.filter()
    context = {
        'doadores': doadores
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def edit_doador(request, id_doador):
    template_name = 'doadores/add_doador.html'
    context ={}
    doador = get_object_or_404(Doador, id=id_doador)
    if request.method == 'POST':
        form = DoadorForm(request.POST, instance=doador)
        if form.is_valid():
            form.save()
            return redirect('doadores:list_doadores')
    form = DoadorForm(instance=doador)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_doador(request, id_doador):
    doador = Doador.objects.get(id=id_doador)
    doador.delete()
    return redirect('doadores:list_doadores')

templates/doadores/add_doador.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Doador - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Doador</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                   <label class="label_txt" for="{{ form.name.id_for_label }}">Nome</label>
                   {{ form.name|add_class:"form-control campotxt-style" }}
                </div>
                <div class="form-group">
                    <label class="label_txt" for="{{ form.cpf.id_for_label }}">CPF</label>
                    {{ form.cpf|add_class:"form-control campotxt-style" }}
                 </div>
                 <div class="form-group">
                    <label class="label_txt" for="{{ form.address.id_for_label }}">Endereço</label>
                    {{ form.address|add_class:"form-control campotxt-style" }}
                 </div>
                 <div class="form-group">
                    <label class="label_txt" for="{{ form.phone.id_for_label }}">Telefone</label>
                    {{ form.phone|add_class:"form-control campotxt-style" }}
                 </div>
                    <button id="botao_salvar" type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>

{% endblock body %}

templates/doadores/list_doadores.html
{% extends 'base.html' %}

{% block title %}

    Lista de Doadores - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Doadores</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'doadores:add_doador' %}">Cadastro de novo doador</a>
                <br />
                <br />
                <table class="tabela">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">CPF</th>
                    <th scope="col">Endereço</th>
                    <th scope="col">Telefone</th>
                    </tr>
                </thead>
                <tbody>
                    {% for doador in doadores %}
                        <tr>
                            <th id="num" scope="row">{{ doador.id }}</th>
                            <td>{{ doador.name }}</td>
                            <td>{{ doador.cpf }}</td>
                            <td>{{ doador.address }}</td>
                            <td>{{ doador.phone }}</td>
                            <td>
                                <a href="{% url 'doadores:edit_doador' doador.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>
                                <a href="{% url 'doadores:delete_doador' doador.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}