apps/animais/urls.py
from django.urls import path
from . import views

app_name = 'animais'

urlpatterns = [
    path('', views.list_animais, name='list_animais'),
    path('adicionar/', views.add_animal, name='add_animal'),
    path('editar/<int:id_animal>/', views.edit_animal, name='edit_animal'),
    path('excluir/<int:id_animal>/', views.delete_animal, name='delete_animal'),
    path('buscar/', views.search_animais, name='search_animais'),
]

projetoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('accounts.urls', namespace='accounts')),
    path('adocoes/', include('adocoes.urls', namespace='adocoes')),
    path('atendimentos/', include('atendimentos.urls', namespace='atendimentos')),
    path('animais/', include('animais.urls', namespace='animais')),
    path('adotantes/', include('adotantes.urls', namespace='adotantes')),
    path('doadores/', include('doadores.urls', namespace='doadores')),
    path('ongs/', include('ongs.urls', namespace='ongs')),
    path('veterinarios/', include('veterinarios.urls', namespace='veterinarios')),
    path('', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/animais/models.py
from django.db import models
from ongs.models import Ong
from doadores.models import Doador

# Create your models here.

class Animal(models.Model):
    create_on = models.DateTimeField(auto_now_add=True)
    update_on = models.DateTimeField(auto_now=True)
    name = models.CharField('Nome', max_length=50)
    SEX_CHOICES = [
        ('Macho', 'Macho'),
        ('Fêmea', 'Fêmea'),
    ]
    sex = models.CharField('Sexo', max_length=5, choices=SEX_CHOICES, default='Macho')
    years_old_value = models.PositiveIntegerField('Idade', default= 0)
    years_old_unit = models.CharField('Unidade de Idade', max_length=10, choices=[
        ('anos', 'Anos'),
        ('meses', 'Meses'),
    ], default='meses')
    SPECIE_CHOICES = [
        ('Gato', 'Gato'),
        ('Cachorro', 'Cachorro'),
    ] 
    specie = models.CharField('Especie', max_length=10, choices=SPECIE_CHOICES, default='Cachorro')
    race = models.CharField('Raca', max_length=10)
    color = models.CharField('Cor', max_length=10)
    weight_value = models.PositiveIntegerField('Peso',  default= 0)
    weight_unit = models.CharField('Unidade de Peso', max_length=10, choices=[
        ('gramas', 'Gramas'),
        ('quilos', 'Quilos'),
    ], default='gramas')
    height_value = models.PositiveIntegerField('Altura', default= 0)
    height_unit = models.CharField('Unidade de Altura', max_length=11, choices=[
        ('centimetros', 'Centímetros'),
        ('metros', 'Metros'),
    ], default= 'metros')
    ong = models.ForeignKey(Ong, on_delete=models.CASCADE, default=1)
    donator = models.ForeignKey(Doador, on_delete=models.CASCADE, default=1)

    @property
    def formatted_years_old(self):
        return f"{self.years_old_value} {self.years_old_unit}"

    @property
    def formatted_weight(self):
        return f"{self.weight_value} {self.weight_unit}"

    @property
    def formatted_height(self):
        return f"{self.height_value} {self.height_unit}"

    class Meta:
        verbose_name = 'Animal'
        verbose_name_plural = 'Animais'
        ordering =['id']
        
    def __str__(self):
        return "%s - %s - %s - %s - %s" % (self.name, self.specie, self.sex, self.race, self.ong)

apps/animais/forms.py
from django import forms
from .models import Animal

class AnimalForm(forms.ModelForm):
    
    class Meta:
        model = Animal
        exclude = ('created_on', 'updated_on',)

apps/animais/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from .forms import AnimalForm
from .models import Animal
from ongs.models import Ong
from django.contrib.auth.decorators import login_required
# Create your views here.

def add_animal(request):
    template_name = 'animais/add_animal.html'
    context = {}
    if request.method == 'POST':
        form = AnimalForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('animais:list_animais')
    form = AnimalForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_animais(request):
    template_name = 'animais/list_animais.html'
    animais = Animal.objects.filter()
    context = {
        'animais': animais
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def edit_animal(request, id_animal):
    template_name = 'animais/add_animal.html'
    context ={}
    animal = get_object_or_404(Animal, id=id_animal)
    if request.method == 'POST':
        form = AnimalForm(request.POST, instance=animal)
        if form.is_valid():
            form.save()
            return redirect('animais:list_animais')
    form = AnimalForm(instance=animal)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_animal(request, id_animal):
    animal = Animal.objects.get(id=id_animal)
    animal.delete()
    return redirect('animais:list_animais')

def search_animais(request):
    template_name = 'animais/list_animais.html'
    query = request.GET.get('query')
    animais = Animal.objects.filter(name__icontains=query)
    context = {
        'animais': animais,
    }
    return render(request,template_name, context)

templates/animais/add_animal.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Animal - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Animal</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST"> <!--enctype="multipart/form-data">-->
                {% csrf_token %}
                <div class="form-group">
                   <label class="label_txt" for="{{ form.name.id_for_label }}">Nome</label>
                   {{ form.name|add_class:"form-control campotxt-style" }}
                </div>
                <div class="form-group">
                    <label class="label_txt" for="{{ form.sex.id_for_label }}">Sexo</label>
                    {{ form.sex|add_class:"form-control campotxt-style" }}
                </div>
                <div class="form-group row">
                    <div class="col-md-6">
                        <label class="label_txt" for="{{ form.years_old_value.id_for_label }}">Idade</label>
                        {{ form.years_old_value|add_class:"form-control campotxt-style" }}
                    </div>
                    <div class="col-md-6">
                        <label class="label_txt" for="{{ form.years_old_unit.id_for_label }}">Selecione</label>
                        {{ form.years_old_unit|add_class:"form-control campotxt-style" }}
                    </div>
                </div>
                <div class="form-group">
                    <label class="label_txt" for="{{ form.specie.id_for_label }}">Espécie</label>
                    {{ form.specie|add_class:"form-control campotxt-style" }}
                </div>
                <div class="form-group">
                    <label class="label_txt" for="{{ form.race.id_for_label }}">Raça</label>
                    {{ form.race|add_class:"form-control campotxt-style" }}
                </div>
                <div class="form-group">
                    <label class="label_txt" for="{{ form.color.id_for_label }}">Cor</label>
                    {{ form.color|add_class:"form-control campotxt-style" }}
                </div>
                <div class="form-group row">
                    <div class="col-md-6">
                        <label class="label_txt" for="{{ form.weight_value.id_for_label }}">Peso</label>
                        {{ form.weight_value|add_class:"form-control campotxt-style" }}
                    </div>
                    <div class="col-md-6">
                        <label class="label_txt" for="{{ form.weight_unit.id_for_label }}">Selecione</label>
                        {{ form.weight_unit|add_class:"form-control campotxt-style" }}
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-6">
                        <label class="label_txt" for="{{ form.height_value.id_for_label }}">Altura</label>
                        {{ form.height_value|add_class:"form-control campotxt-style" }}
                    </div>
                    <div class="col-md-6">
                        <label class="label_txt" for="{{ form.height_unit.id_for_label }}">Selecione</label>
                        {{ form.height_unit|add_class:"form-control campotxt-style" }}
                    </div>
                </div>
                <div class="form-group">
                    <label class="label_txt" for="{{ form.ong.id_for_label }}">Ong</label>
                    {{ form.ong|add_class:"form-control campotxt-style" }}
                </div>
                <div class="form-group">
                    <label class="label_txt" for="{{ form.donator.id_for_label }}">Doador</label>
                    {{ form.donator|add_class:"form-control campotxt-style" }}
                </div>
                    <button id="botao_salvar" type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>


{% endblock body %}

templates/animais/list_animais.html
{% extends 'base.html' %}

{% block title %}

    Lista de Animais - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Animais</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'animais:add_animal' %}">Cadastro de Animal</a>
                <br />
                <br />
                <table class="tabela">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Sexo</th>
                    <th scope="col">Idade</th>
                    <th scope="col">Espécie</th>
                    <th scope="col">Raça</th>
                    <th scope="col">Cor</th>
                    <th scope="col">Peso</th>
                    <th scope="col">Altura</th>
                    <th scope="col">Ong</th>
                    <th scope="col">Doador</th>
                    </tr>
                </thead>
                <tbody>
                    {% for animal in animais %}
                        <tr>
                            <th id="num" scope="row">{{ animal.id }}</th>
                            <td>{{ animal.name }}</td>
                            <td>{{ animal.get_sex_display }}</td>
                            <td>
                                {{ animal.years_old_value }}
                                {% if animal.years_old_unit == 'anos' %}
                                    a
                                {% else %}
                                    m
                                {% endif %}
                            </td>
                            <td>{{ animal.get_specie_display }}</td>
                            <td>{{ animal.race }}</td>
                            <td>{{ animal.color }}</td>
                            <td>
                                {{ animal.weight_value }}
                                {% if animal.weight_unit == 'quilos' %}
                                    kg
                                {% else %}
                                    g
                                {% endif %}
                            </td>
                            <td>{{ animal.height_value }}
                                {% if animal.height_unit == 'metros' %}
                                    m
                                {% else %}
                                    cm
                                {% endif %}
                            </td>
                            <td>{{ animal.ong }}</td>
                            <td>{{ animal.donator }}</td>
                            <td>
                                <a href="{% url 'animais:edit_animal' animal.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>    
                                <a href="{% url 'animais:delete_animal' animal.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}