apps/adocoes/urls.py
from django.urls import path
from . import views

app_name = 'adocoes'

urlpatterns = [
    path('', views.list_adocoes, name='list_adocoes'),
    path('adicionar/', views.add_adocao, name='add_adocao'),
    path('editar/<int:id_adocao>/', views.edit_adocao, name='edit_adocao'),
    path('excluir/<int:id_adocao>/', views.delete_adocao, name='delete_adocao'),
]

apps/animais/urls.py
from django.urls import path
from . import views

app_name = 'animais'

urlpatterns = [
    path('', views.list_animais, name='list_animais'),
    path('adicionar/', views.add_animal, name='add_animal'),
    path('editar/<int:id_animal>/', views.edit_animal, name='edit_animal'),
    path('excluir/<int:id_animal>/', views.delete_animal, name='delete_animal'),
    path('buscar/', views.search_animais, name='search_animais'),
]

apps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
]

apps/ongs/urls.py
from django.urls import path
from . import views

app_name = 'ongs'

urlpatterns = [
    path('', views.list_ongs, name='list_ongs'),
    path('adicionar/', views.add_ong, name='add_ong'),
    path('editar/<int:id_ong>/', views.edit_ong, name='edit_ong'),
    path('excluir/<int:id_ong>/', views.delete_ong, name='delete_ong'),
]

projetoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('accounts.urls', namespace='accounts')),
    path('adocoes/', include('adocoes.urls', namespace='adocoes')),
    path('atendimentos/', include('atendimentos.urls', namespace='atendimentos')),
    path('animais/', include('animais.urls', namespace='animais')),
    path('adotantes/', include('adotantes.urls', namespace='adotantes')),
    path('doadores/', include('doadores.urls', namespace='doadores')),
    path('ongs/', include('ongs.urls', namespace='ongs')),
    path('veterinarios/', include('veterinarios.urls', namespace='veterinarios')),
    path('', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="https://cdn-icons-png.flaticon.com/512/35/35097.png" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <title>{% block title %}SOS Bicharada Home{% endblock title %}</title>
</head>
<body id="corpo">
 <!-- INICIO: Bloco do Bootstrap a ser incluido -->
<nav id="barra_nav" class="navbar navbar-expand-lg" href="/"> <img src="https://cdn-icons-png.flaticon.com/512/35/35097.png" alt="logo" class="imagem_logo"><a href="{% url 'core:home' %}" id="nome_header" class="navbar-brand">SOS Bicharada</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    {% if user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarsExample05">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"  href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >Adotante</a>
                <div class="dropdown-menu" aria-labelledby="dropdown05">
                    <a class="dropdown-item" href="{% url 'adotantes:add_adotante' %}">Quero Adotar</a>
                    <a class="dropdown-item" href="{% url 'adotantes:list_adotantes' %}">Lista de Adotantes</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"  href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >Doador</a>
                <div class="dropdown-menu" aria-labelledby="dropdown05">
                    <a class="dropdown-item" href="{% url 'doadores:add_doador' %}">Quero Doar</a>
                    <a class="dropdown-item" href="{% url 'doadores:list_doadores' %}">Lista de Doadores</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Veterinário</a>
                <div class="dropdown-menu" aria-labelledby="dropdown05">
                    <a class="dropdown-item" href="{% url 'veterinarios:add_veterinario' %}">Cadastrar Veterinário</a>
                    <a class="dropdown-item" href="{% url 'veterinarios:list_veterinarios' %}">Lista de Veterinários</a>
                    <a class="dropdown-item" href="{% url 'atendimentos:add_atendimento' %}">Cadastrar Atendimento</a>
                    <a class="dropdown-item" href="{% url 'atendimentos:list_atendimentos' %}">Lista de Atendimentos</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ong</a>
                <div class="dropdown-menu" aria-labelledby="dropdown05">
                    <a class="dropdown-item" href="{% url 'ongs:add_ong' %}">Cadastrar Ong</a>
                    <a class="dropdown-item" href="{% url 'ongs:list_ongs' %}">Lista de Ongs</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expand="false">Animais</a>
                <div class="dropdown-menu" aria-labelledby="dropdown05">
                    <a class="dropdown-item" href="{% url 'animais:add_animal' %}">Cadastrar Animal</a>
                    <a class="dropdown-item" href="{% url 'animais:list_animais' %}">Lista de Animais</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown06" data-toggle="dropdown" aria-haspopup="true" aria-expand="false">Adoção</a>
                <div class="dropdown-menu" aria-labelledby="dropdown05">
                    <a class="dropdown-item" href="{% url 'adocoes:add_adocao' %}">Cadastrar Adoção</a>
                    <a class="dropdown-item" href="{% url 'adocoes:list_adocoes' %}">Lista de Adoções</a>
                </div>
            </li>
            <form id="barra_buscar" action="{% url 'animais:search_animais' %}"  method="GET" class="form-inline my-2 my-md-0">
                <input id="campo_buscar" class="form-control" name="query" type="text" placeholder="Nome do animal" aria-label="Buscar">
                <button id="botao_buscar" class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Buscar</button>
            </form>
            <ul id="campo_conta" class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown08" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.get_full_name|default:user.username }}</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown05">
                        <a class="dropdown-item" href="{% url 'accounts:user_change_information' user.username %}">Conta</a>
                        <a class="dropdown-item" href="{% url 'accounts:user_change_password' %}">Trocar senha</a>
                        <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Sair</a>
                    </div>
                </li>
            </ul>
        </ul>
    </div>
{% endif %}
{% if not user.is_authenticated %}
    <a href="{% url 'accounts:user_login' %}"><button type="button" id="botao_entrar">Login/Cadastrar</button></a>
{% endif %}
</nav>
<!-- FIM: Bloco do Bootstrap a ser incluido -->
    {% block body %}
   
    {% endblock body %}
    
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


    <script src="{% static 'js/ongs.js' %}"></script>
    <script src="{% static 'js/doadores.js' %}"></script>
    <script src="{% static 'js/animais.js' %}"></script>
    <script src="{% static 'js/adotantes.js' %}"></script>
    <script src="{% static 'js/adocoes.js' %}"></script>
    <script src="{% static 'js/veterinarios.js' %}"></script>
    
</body>
</html>