apps/atendimentos/urls.py
from django.urls import path
from . import views

app_name = 'Atendimentos'

urlpatterns = [
    path('', views.list_atendimentos, name='list_atendimentos'),
    path('adicionar/', views.add_atendimento, name='add_atendimento'),
    path('editar/<int:id_atendimento>/', views.edit_atendimento, name='edit_atendimento'),
    path('excluir/<int:id_atendimento>/', views.delete_atendimento, name='delete_atendimento'),
]

projetoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('accounts.urls', namespace='accounts')),
    path('adocoes/', include('adocoes.urls', namespace='adocoes')),
    path('atendimentos/', include('atendimentos.urls', namespace='atendimentos')),
    path('animais/', include('animais.urls', namespace='animais')),
    path('adotantes/', include('adotantes.urls', namespace='adotantes')),
    path('doadores/', include('doadores.urls', namespace='doadores')),
    path('ongs/', include('ongs.urls', namespace='ongs')),
    path('veterinarios/', include('veterinarios.urls', namespace='veterinarios')),
    path('', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/atendimentos/models.py
from django.db import models
from animais.models import Animal
from veterinarios.models import Veterinario

# Create your models here.

class Atendimento(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    reason = models.CharField('Razao', max_length=50)
    description = models.CharField('Descricao', max_length=50)
    medicine = models.CharField('Medicamento', max_length=15)
    vaccine = models.CharField('Vacina', max_length=15)
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE, default=1)
    veterinary = models.ForeignKey(Veterinario, on_delete=models.CASCADE, default=1)
    
    
    class Meta:
        verbose_name = 'Atendimento'
        verbose_name_plural = 'Atendimentos'
        ordering =['id']

    def __str__(self):
        return self.reason

apps/atendimentos/forms.py
from django import forms
from .models import Atendimento

class AtendimentoForm(forms.ModelForm):
    
    class Meta:
        model = Atendimento
        exclude = ('created_on', 'updated_on',)

apps/atendimentos/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from .forms import AtendimentoForm
from .models import Atendimento
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='/contas/login/')
def add_atendimento(request):
    template_name = 'atendimentos/add_atendimento.html'
    context = {}
    if request.method == 'POST':
        form = AtendimentoForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('atendimentos:list_atendimentos')
    form = AtendimentoForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_atendimentos(request):
    template_name = 'atendimentos/list_atendimentos.html'
    atendimentos = Atendimento.objects.filter()
    context = {
        'atendimentos': atendimentos
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def edit_atendimento(request, id_atendimento):
    template_name = 'atendimentos/add_atendimento.html'
    context ={}
    atendimento = get_object_or_404(Atendimento, id=id_atendimento)
    if request.method == 'POST':
        form = AtendimentoForm(request.POST, request.FILES,  instance=atendimento)
        if form.is_valid():
            form.save()
            return redirect('atendimentos:list_atendimentos')
    form = AtendimentoForm(instance=atendimento)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_atendimento(request, id_atendimento):
    atendimento = Atendimento.objects.get(id=id_atendimento)
    atendimento.delete()
    return redirect('atendimentos:list_atendimentos')

templates/atendimentos/add_atendimento.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Atendimento - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Atendimento</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST"> <!--enctype="multipart/form-data"> -->
                {% csrf_token %}
                <div class="form-group">
                   <label class="label_txt" for="{{ form.reason.id_for_label }}">Motivo</label>
                   {{ form.reason|add_class:"form-control campotxt-style" }}
                </div>
                <div class="form-group">
                    <label class="label_txt" for="{{ form.description.id_for_label }}">Descrição</label>
                    {{ form.description|add_class:"form-control campotxt-style" }}
                </div>
                <div class="form-group">
                    <label class="label_txt" for="{{ form.medicine.id_for_label }}">Medicamento</label>
                    {{ form.medicine|add_class:"form-control campotxt-style" }}
                </div>
                <div class="form-group">
                    <label class="label_txt" for="{{ form.vaccine.id_for_label }}">Vacina</label>
                    {{ form.vaccine|add_class:"form-control campotxt-style" }}
                </div>
                <div class="form-group">
                    <label class="label_txt" for="{{ form.animal.id_for_label }}">Animal</label>
                    {{ form.animal|add_class:"form-control campotxt-style" }}
                </div>
                <div class="form-group">
                    <label class="label_txt" for="{{ form.veterinary.id_for_label }}">Veterinário</label>
                    {{ form.veterinary|add_class:"form-control campotxt-style" }}
                </div>
                    <button id="botao_salvar" type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/atendimentos/list_atendimentos.html
{% extends 'base.html' %}

{% block title %}

    Lista de Atendimentos - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Atendimentos</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'atendimentos:add_atendimento' %}">Cadastro de Atendimento</a>
                <br />
                <br />
                <table class="tabela">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Motivo</th>
                    <th scope="col">Descrição</th>
                    <th scope="col">Medicamento</th>
                    <th scope="col">Vacina</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Veterinário</th>
                    </tr>
                </thead>
                <tbody>
                    {% for atendimento in atendimentos %}
                        <tr>
                            <th id="num" scope="row">{{ atendimento.id }}</th>
                            <td>{{ atendimento.reason }}</td>
                            <td>{{ atendimento.description }}</td>
                            <td>{{ atendimento.medicine }}</td>
                            <td>{{ atendimento.vaccine }}</td>
                            <td>{{ atendimento.animal }}</td>
                            <td>{{ atendimento.veterinary }}</td>
                            <td>
                                <a href="{% url 'atendimentos:edit_atendimento' atendimento.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>    
                                <a href="{% url 'atendimentos:delete_atendimento' atendimento.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}